### ISSUE TITLE
Hard Dependency on angular-material@1.0.8 necessary ? 

### ISSUE THREAD

**Issue by akkumar** [zhentian-wan/angular-md-table#11]
package.json refers to a hard dependency on angular-material@1.0.8 ( and angular@1.5.2 ) as well . 

Was wondering if that is necessary ? The latest releases of angularjs seem to be angularjs 1.6.4 and material 1.1.4 . Is there anything that you are aware that would break angular-md-table ? 

If not - may be - can we have a more relaxed dependency specification in package.json ? ( may be, a >= )

Thanks in advance for the help. 

https://blog.nodejitsu.com/package-dependencies-done-right/

**Comment by zhentian-wan** [comment]
@akkumar Humm... Sorry for misleading... 

Actually that was my development & testing env...

After build, there is no Angular & Angular Material files inside the bundle. It depends on your dev env.
I think it should be fine to use Angular1.6 and Material 1.4 in your env.

**Comment by akkumar** [comment]
So -in that case, can you change the dependencies in package.json to indicate that it is flexible with the releases of angular-material and angular and make a minor release (of angular-md-table) if possible, so I can pick up the changes ? 

Currently because of the hard dependency, it is becoming a bit of an issue, as I am forced to be with angular-material@1.0.8 .

**Comment by zhentian-wan** [comment]
I don't get it why it is a issue, could you provide any screenshot or error message? That would be helpful.

Because we have used Material v1.1.3, it is totally fine.

And I cannot do what you said, '>=' may introduce bug which you never know. The reason behind this, please check https://medium.com/@kentcdodds/why-semver-ranges-are-literally-the-worst-817cdcb09277
